// SPEC:     docs/00-COMPONENTS/2.7/04-LipiValidationSummary-Spec.md §4
// PHASE:    Phase 2 Sub-step 2.7 — Feedback Components family
// AMEND:    docs/CHANGE-LOG.md A35 (2026-05-15)
//
// Type definitions for LipiValidationSummary. Pattern matches sibling
// Phase 2.7 *Types.cs files — short enum names without Lipi prefix, colocated
// with consuming component in LiPi.Web.Components.Shared.
//
// ValidationError is a class (not record) so consumers can construct via
// initializer syntax AND modify after construction. FieldName is the only
// strictly required value; DisplayName, FieldId, and Message all have
// sensible fallbacks.

namespace LiPi.Web.Components.Shared;

/// <summary>
/// Display mode for LipiValidationSummary. Compact shows a single-line
/// summary count; Detailed (default) shows the full bulleted list of errors.
/// </summary>
public enum ValidationSummaryMode
{
    /// <summary>Single line: "⚠ 6 errors. Please fix them before saving."
    /// Use for very long forms where a full bulleted list would itself be
    /// overwhelming.</summary>
    Compact,

    /// <summary>Full bulleted list of errors with click-to-field navigation.
    /// Default for standard forms.</summary>
    Detailed
}

/// <summary>
/// Placement of the validation summary within an EditForm. <c>Both</c> is a
/// bit-flag combination (Top | Bottom) and renders the same summary twice —
/// useful for very long forms (25+ fields) where the user may not scroll
/// back to the top after clicking Save.
/// </summary>
[Flags]
public enum ValidationSummaryPlacement
{
    /// <summary>Above the first form field (default).</summary>
    Top    = 1,

    /// <summary>Above the submit button area.</summary>
    Bottom = 2,

    /// <summary>Renders at both top AND bottom of the form.</summary>
    Both   = Top | Bottom
}

/// <summary>
/// A single validation error for LipiValidationSummary. Created by the
/// EditContext auto-discovery path or supplied explicitly by the consumer
/// (e.g., server-returned errors after a save attempt).
/// </summary>
public class ValidationError
{
    /// <summary>
    /// Property name from the model — e.g., <c>"FirstName"</c>. The special
    /// value <c>"*"</c> indicates a top-level error not tied to a specific
    /// field (in EditContext terms, the "object FieldIdentifier").
    /// </summary>
    public string FieldName { get; set; } = "";

    /// <summary>
    /// The validation message — e.g., <c>"is required"</c>. Displayed after
    /// <see cref="DisplayName"/> in the summary list: "First name is required".
    /// </summary>
    public string Message { get; set; } = "";

    /// <summary>
    /// User-friendly field label — e.g., <c>"First name"</c>. Pulled from the
    /// model property's <c>[Display(Name = "...")]</c> attribute when
    /// available, otherwise generated by PascalCase-to-space conversion of
    /// <see cref="FieldName"/>.
    /// </summary>
    public string? DisplayName { get; set; }

    /// <summary>
    /// HTML <c>id</c> of the field for click-to-scroll navigation. When set,
    /// the summary item renders as an anchor link; clicking scrolls the field
    /// into view, focuses it, and flashes the highlight ring.
    /// </summary>
    public string? FieldId { get; set; }

    /// <summary>Default constructor — initializer-syntax friendly.</summary>
    public ValidationError() { }

    /// <summary>Convenience constructor for the common "field + message" case.</summary>
    public ValidationError(string fieldName, string message)
    {
        FieldName = fieldName;
        Message = message;
    }
}
